version: '3.8'

services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - trading-net
    command: redis-server --save 60 1 --loglevel warning

volumes:
  redis-data:

networks:
  trading-net:
    driver: bridge
